jobs:

  - name: openssl_tester
    type: runSh
    allowPublicAccess: true
    steps:
      - TASK:
          name: openssl custom image
          runtime:
            container: true
            options:
              imageName: gvancuts/clearlinux-acrn-build
              imageTag: latest
          script:
            - openssl version

